In [ ]:
from google.colab import files
uploaded = files.upload()

Saving avionics_dataset .csv.csv to avionics_dataset .csv.csv

In [ ]:
import pandas as pd
df = pd.read_csv('avionics_dataset .csv.csv')
df.head()

,id,packet_size,source_node,destination_node,delay,protocol,frequency,label
0,1,1417.0,FCC-1,IRS-1,0.667,MIL-STD-1553,878.7,attack
1,2,517.0,FMS-2,EFIS-R,3.676,MIL-STD-1553,104.0,attack
2,3,503.0,ADIRU-2,EFIS-R,3.447,AFDX,91.7,normal
3,4,542.0,ADIRU-1,EFIS-R,4.099,MIL-STD-1553,95.6,normal
4,5,499.0,ADIRU-1,FMS-1,4.531,AFDX,88.3,attack

In [ ]:
df.head()

,id,packet_size,source_node,destination_node,delay,protocol,frequency,label
0,1,1417.0,FCC-1,IRS-1,0.667,MIL-STD-1553,878.7,attack
1,2,517.0,FMS-2,EFIS-R,3.676,MIL-STD-1553,104.0,attack
2,3,503.0,ADIRU-2,EFIS-R,3.447,AFDX,91.7,normal
3,4,542.0,ADIRU-1,EFIS-R,4.099,MIL-STD-1553,95.6,normal
4,5,499.0,ADIRU-1,FMS-1,4.531,AFDX,88.3,attack

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['source_node_enc']      = le.fit_transform(df['source_node'])
df['destination_node_enc'] = le.fit_transform(df['destination_node'])
df['protocol_enc']         = le.fit_transform(df['protocol'])

In [ ]:
features = ['packet_size', 'source_node_enc', 'destination_node_enc',
            'delay', 'protocol_enc', 'frequency']

X = df[features]
y = (df['label'] == 'attack').astype(int)  # 0 = normal, 1 = attack

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred, target_names=['Normal', 'Attack']))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

      Normal       0.83      0.97      0.90        40
      Attack       0.92      0.60      0.73        20

    accuracy                           0.85        60
   macro avg       0.88      0.79      0.81        60
weighted avg       0.86      0.85      0.84        60

[[39  1]
 [ 8 12]]

In [ ]:
import pandas as pd

importance = pd.Series(clf.feature_importances_, index=features).sort_values(ascending=False)
print(importance)

frequency               0.307676
packet_size             0.281580
delay                   0.245864
destination_node_enc    0.061858
source_node_enc         0.055856
protocol_enc            0.047166
dtype: float64

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred, target_names=['Normal', 'Attack']))

              precision    recall  f1-score   support

      Normal       0.83      0.97      0.90        40
      Attack       0.92      0.60      0.73        20

    accuracy                           0.85        60
   macro avg       0.88      0.79      0.81        60
weighted avg       0.86      0.85      0.84        60